import { Geist, Geist_Mono } from "next/font/google";
import SocketListener from "@/components/SocketListener"; // Namma create panna component
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Grand Cinemas - Smart Parking",
  description: "Generated by YOGARAJ M",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* WebSocket Global Listener */}
        <SocketListener />
        
        {/* Page Contents */}
        {children}
      </body>
    </html>
  );
}